### ISSUE TITLE
项目运行之后怎么上传私库呢

### ISSUE THREAD

**Issue by Zeeyeee** [nilppm/npm#1]
运行之后数据库的package里一个包也没有，要上传库文件也不知道怎么上传

**Comment by cevio** [comment]
> 运行之后数据库的package里一个包也没有，要上传库文件也不知道怎么上传

https://github.com/nilppm/cli 看下这里有说明。上传的话，就是简单的`cpm publish`。私有包肯定是要自己上传才有的。不是像cnpm那样的自动同步，我想你的磁盘也吃不消。简单来说，就是一个私有小型的npm

**Comment by cevio** [comment]
这里注意下，cpm只能上传你在nilppm.config.js中指定的scope域开头的包。
