### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by xxxsf** [nilppm/npm#2]
请问，“不涉及同步模式，同步模式带来的磁盘开销太大”。那么有的包不翻墙无法安装是怎么解决的？

**Comment by cevio** [comment]
@allan2coder 内置了优先从淘宝源获取，所以国内不需要翻墙，理论上速度和淘宝源相等。

**Comment by xxxsf** [comment]
好的，与我想的预期一样。那么通过 cnpm 在本地搭建的私有包管理默认就是这种同步模式吧，而你改了这种模式。

**Comment by cevio** [comment]
> 好的，与我想的预期一样。那么通过 cnpm 在本地搭建的私有包管理默认就是这种同步模式吧，而你改了这种模式。

@allan2coder cnpm也是从淘宝源优先拉取的。我的是可以配置的。只是我没有公开这个属性(https://github.com/nilppm/npm/blob/master/src/service/package.ts#L243)。

我跟cnpm的区别是更加轻量化。cnpm太重了。安装又很麻烦。
